name: AUTO_Merge Enhanced EPG

on:
  workflow_run:
    workflows:
      - AUTO_Update requested EPG XML (Australia)
    types:
      - completed

  workflow_dispatch:  # Manual trigger

jobs:
  merge-enhanced-epg:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run merge enrichment script
        run: |
          python3 Backflow/scripts/B_merge_enrich.py

      - name: Commit and push merged EPG
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add Master_Location/Sydney_enhanced_EPG.xml
          git commit -m "Merged enriched EPG $(date +%Y-%m-%d)" || echo "No changes to commit"
          git pull --rebase --autostash
          git push
