name: AUTO_Update requested EPG XML (Australia)

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  workflow_dispatch:

jobs:
  enrich-epg:
    runs-on: ubuntu-latest
    env:
      TRAKT_CLIENT_ID: ${{ secrets.TRAKT_CLIENT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create output folder if it doesn't exist
        run: mkdir -p Backflow/Manual_Database

      - name: Download multiple EPG XML files from list
        run: |
          while IFS='|' read -r filename url || [[ -n "$filename" ]]; do
            # Skip empty lines or lines starting with #
            if [[ -z "$filename" || "$filename" == \#* ]]; then
              continue
            fi
            url_expanded=$(echo "$url" | sed "s/\$(date +%Y%m%d)/$(date +%Y%m%d)/g")
            echo "Downloading $filename from $url_expanded"
            curl -s -o "Backflow/Manual_Database/$filename" "$url_expanded"
          done < Backflow/scripts/epg/EPG_list.txt

      - name: Correct episode numbers in downloaded EPG XML files
        run: |
          for script in Backflow/scripts/epg/*.py; do
            echo "Running $script"
            python3 "$script"
          done

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add Backflow/Manual_Database/
          git commit -m "Updated EPG XML files $(date +%Y-%m-%d)" || echo "No changes to commit"
          git pull --rebase --autostash
          git push
