name: AUTO_Update requested EPG XML (Australia)

on:
  workflow_run:
    workflows:
      - Download and correct Sydney EPG Metadata
    types:
      - completed

  workflow_dispatch:   # Allows manual trigger for testing

jobs:
  enrich-epg:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    env:
      TRAKT_CLIENT_ID: ${{ secrets.TRAKT_CLIENT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create output folder if it doesn't exist
        run: mkdir -p Backflow/Manual_Database

      - name: Download all EPG XMLs from list
        run: |
          while IFS='|' read -r filename url; do
            echo "Downloading $filename from $url"
            expanded_url=$(echo "$url" | sed "s/\$(date +%Y%m%d)/$(date +%Y%m%d)/g")
            curl -sSfL -o "Backflow/Manual_Database/$filename" "$expanded_url"
          done < Backflow/scripts/epg/EPG_list.txt

      - name: Correct episode numbers in all downloaded EPG XMLs
        run: |
          for file in Backflow/Manual_Database/*.xml; do
            echo "Correcting episodes in $file"
            python3 Backflow/scripts/A_episode_corrector.py "$file" "$file"
          done
          
      - name: Enrich South Park
        run: python3 Backflow/scripts/epg/enrich_southpark.py Backflow/Manual_Database/AU-South_Park.xml

      - name: Enrich Judge Judy
        run: python3 Backflow/scripts/epg/enrich_judgejudy.py Backflow/Manual_Database/AU-Judge_Judy.xml


      - name: Commit and push all changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add Backflow/Manual_Database/*.xml
          git commit -m "Updated EPG XMLs $(date +%Y-%m-%d)" || echo "No changes to commit"
          git pull --rebase --autostash
          git push
