name: Download and correct Sydney EPG Metadata

on:
  schedule:
    - cron: '0 14 * * *'  # Daily at midnight AEST (UTC+10)
  workflow_dispatch:

jobs:
  update-merge-epg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create required folders
        run: |
          mkdir -p Backflow/Base_EPG_XML
          mkdir -p Backflow/Manual_Database
          mkdir -p Master_Location

      - name: Download base Sydney EPG XML
        run: |
          curl -o Backflow/Base_EPG_XML/base_syd.xml "https://raw.githubusercontent.com/matthuisman/i.mjh.nz/refs/heads/master/au/Sydney/epg.xml"

      - name: Commit and push downloaded base EPG
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add Backflow/Base_EPG_XML/base_syd.xml
          git commit -m "Add base Sydney EPG $(date +%Y-%m-%d)" || echo "No changes to commit"
          git push

      - name: Correct episode numbers in base EPG (in place)
        run: |
          python3 Backflow/scripts/A_episode_corrector.py Backflow/Base_EPG_XML/base_syd.xml

      - name: Commit and push corrected EPG
        run: |
          git add Backflow/Base_EPG_XML/base_syd.xml
          git commit -m "Correct episode numbers in Sydney EPG $(date +%Y-%m-%d)" || echo "No changes to commit"
          git push
