name: Enrich Hallmark Golden Girls Episodes

on:
  workflow_dispatch:

jobs:
  enrich:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install rapidfuzz

      - name: Run enrichment script
        run: python Backflow/scripts/enrich_hallmark_golden_girls.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add individual/USA-Hallmark_EastUS.xml
          git diff --quiet && git diff --staged --quiet || git commit -m "Enriched Hallmark Golden Girls using episode DB"
          git push --force
