name: Enrich The Golden Girls with TVmaze Episode Titles

on:
  workflow_dispatch:

jobs:
  enrich:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run enrichment script
      run: |
        python Backflow/scripts/enrich_golden_girls.py

    - name: Commit and push changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add Backflow/offline/episodes/The_Golden_Girls.xml
        git commit -m "Enriched The Golden Girls with episode subtitles via TVmaze" || echo "No changes to commit"
        git push
