name: Enrich The Golden Girls with TVmaze Episode Titles

on:
  workflow_dispatch:

jobs:
  enrich:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Write enrichment script
      run: |
        mkdir -p scripts
        cat << 'EOF' > scripts/enrich_golden_girls.py
import xml.etree.ElementTree as ET
import requests
import time

file_path = "Backflow/offline/episodes/The_Golden_Girls.xml"
tvmaze_show_id = 530  # TVmaze ID for "The Golden Girls"

episode_cache = {}

def get_episode_name(season, episode):
    key = f"S{season:02d}E{episode:02d}"
    if key in episode_cache:
        return episode_cache[key]
    url = f"https://api.tvmaze.com/shows/{tvmaze_show_id}/episodebynumber?season={season}&number={episode}"
    response = requests.get(url)
    if response.status_code == 200:
        title = response.json().get("name", "")
        episode_cache[key] = title
        return title
    return ""

tree = ET.parse(file_path)
root = tree.getroot()

for programme in root.findall("programme"):
    ep_tag = programme.find("./episode-num[@system='SxxExx']")
    if ep_tag is None or not ep_tag.text:
        continue
    epcode = ep_tag.text.strip()
    match = epcode.upper().replace("S", "").split("E")
    if len(match) != 2:
        continue
    try:
        season = int(match[0])
        episode = int(match[1])
    except ValueError:
        continue
    episode_name = get_episode_name(season, episode)
    if not episode_name:
        continue
    subtitle_text = f"{episode_name} – {epcode}"
    title_tag = programme.find("title")
    if title_tag is not None:
        subtitle_tag = ET.Element("sub-title")
        subtitle_tag.text = subtitle_text
        title_index = list(programme).index(title_tag)
        programme.insert(title_index + 1, subtitle_tag)
    time.sleep(0.2)

tree.write(file_path, encoding="utf-8", xml_declaration=True)
EOF

    - name: Run enrichment script
      run: python scripts/enrich_golden_girls.py

    - name: Commit and push changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add Backflow/offline/episodes/The_Golden_Girls.xml
        git commit -m "Enriched The Golden Girls with episode subtitles via TVmaze" || echo "No changes to commit"
        git push
