name: Update and Merge Sydney EPG Metadata

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  workflow_dispatch:

jobs:
  update-merge-epg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create required folders
        run: |
          mkdir -p Backflow/scripts
          mkdir -p Backflow/Manual_Database
          mkdir -p Master_Location

      - name: Download base Sydney EPG XML
        run: |
          curl -o Backflow/scripts/Base_syd.xml "https://raw.githubusercontent.com/matthuisman/i.mjh.nz/refs/heads/master/au/Sydney/epg.xml"

      - name: Apply episode corrector in-place
        run: |
          python3 Backflow/scripts/A_episode_corrector.py Backflow/scripts/Base_syd.xml Backflow/scripts/Base_syd.xml

      - name: Merge enriched metadata from Manual_Database
        run: |
          python3 Backflow/scripts/B_merge_enrich.py --base Backflow/scripts/Base_syd.xml --enriched-dir Backflow/Manual_Database --output Master_Location/Sydney_enhanced_EPG.xml

      - name: Commit and push updated combined EPG
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add Master_Location/Sydney_enhanced_EPG.xml
          git commit -m "Update and merge Sydney EPG metadata $(date +%Y-%m-%d)" || echo "No changes to commit"
          git pull --rebase --autostash
          git push

      - name: Delete base EPG file
        run: |
          rm -f Backflow/scripts/Base_syd.xml
