name: Convert RedbullTV EPG to Sydney Time

on:
  schedule:
    - cron: '10 0 * * *'  # Runs daily at 00:10 UTC
  workflow_dispatch:

jobs:
  convert_epg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create folders if they don't exist
        run: |
          mkdir -p og_time
          mkdir -p individual

      - name: Fetch RedbullTV XML
        run: curl -o og_time/Redbulltv.xml "https://nzxmltv.com/iptv/redbull.xml"

      - name: Convert to Sydney time and output cleaned XML
        run: |
          FILE_IN="og_time/Redbulltv.xml"
          FILE_OUT="individual/Redbulltv.xml"

          echo '<?xml version="1.0" encoding="UTF-8"?>' > "$FILE_OUT"
          echo '<!DOCTYPE tv SYSTEM "xmltv.dtd">' >> "$FILE_OUT"

          # Extract first programme time and convert for <tv date>
          first_start=$(grep -oPm1 '<programme start="\K[^"]+' "$FILE_IN")
          utc_dt="${first_start:0:14}"
          tv_date=$(TZ=Australia/Sydney date -d "${utc_dt:0:4}-${utc_dt:4:2}-${utc_dt:6:2} ${utc_dt:8:2}:${utc_dt:10:2}:${utc_dt:12:2}" +"%Y%m%d%H%M%S %z")

          echo "<tv date=\"$tv_date\">" >> "$FILE_OUT"

          # Include channel block
          sed -n '/<channel /,/<\/channel>/p' "$FILE_IN" >> "$FILE_OUT"

          # Adjust all <programme> blocks
          awk -v TZ="Australia/Sydney" '
            /<programme / {
              match($0, /start="([0-9]{14}) \+0000"/, a)
              start_utc = a[1]
              start_cmd = "TZ=Australia/Sydney date -d \"" substr(start_utc,1,4) "-" substr(start_utc,5,2) "-" substr(start_utc,7,2) " " substr(start_utc,9,2) ":" substr(start_utc,11,2) ":" substr(start_utc,13,2) "\" +\"%Y%m%d%H%M%S\""
              start_local = (start_cmd | getline tmp) > 0 ? tmp : start_utc
              close(start_cmd)

              match($0, /stop="([0-9]{14}) \+0000"/, b)
              stop_utc = b[1]
              stop_cmd = "TZ=Australia/Sydney date -d \"" substr(stop_utc,1,4) "-" substr(stop_utc,5,2) "-" substr(stop_utc,7,2) " " substr(stop_utc,9,2) ":" substr(stop_utc,11,2) ":" substr(stop_utc,13,2) "\" +\"%Y%m%d%H%M%S\""
              stop_local = (stop_cmd | getline tmp2) > 0 ? tmp2 : stop_utc
              close(stop_cmd)

              gsub(/start="[0-9]{14} \+0000"/, "start=\"" start_local " +0000\"", $0)
              gsub(/stop="[0-9]{14} \+0000"/, "stop=\"" stop_local " +0000\"", $0)

              print $0
              next
            }
            { print }
          ' "$FILE_IN" >> "$FILE_OUT"

          echo "</tv>" >> "$FILE_OUT"

      - name: Commit and push if changed
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git pull --rebase --autostash
          git add individual/Redbulltv.xml

          if ! git diff --cached --quiet; then
            git commit -m "RedbullTV EPG converted to Sydney time on $(date -u +%Y-%m-%d)"
            git push
          else
            echo "No changes to commit"
