name: Update EPG XML Sky News AU

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight UTC daily
  workflow_dispatch:  # Allows manual runs

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create individual folder if it doesn't exist
        run: mkdir -p individual

      - name: Fetch EPG XML
        run: curl -o individual/AU-Sky_News.xml "https://epg.pw/api/epg.xml?lang=en&date=$(date +%Y%m%d)&channel_id=421896"

      - name: Add XML Declaration and DOCTYPE
        run: |
          sed -i '1s|$| <!DOCTYPE tv SYSTEM "xmltv.dtd">|' individual/AU-Sky_News.xml

      - name: Add Icon and Categories to All Programmes
        run: |
          sed -i '/<programme /a <icon src="https://www.yodeck.com/wp-content/uploads/2023/06/Sky-news-Thumbnail.jpg"/>\n<category lang="en">Current Affairs</category>\n<category lang="en">News</category>' individual/AU-Sky_News.xml

      - name: Commit and push if changed
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git pull --rebase --autostash
          git add individual/AU-Sky_News.xml
          git commit -m "Updated EPG $(date +%Y-%m-%d)" || echo "No changes to commit"
          git push
