name: Update EPG XML South Park (Australia)

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  workflow_dispatch:

jobs:
  enrich-epg:
    runs-on: ubuntu-latest
    env:
      TRAKT_CLIENT_ID: ${{ secrets.TRAKT_CLIENT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create output folder if it doesn't exist
        run: mkdir -p Backflow/Manual_Database

      - name: Download South Park EPG XML
        run: |
          curl -o Backflow/Manual_Database/AU-South_Park.xml "https://epg.pw/api/epg.xml?lang=en&date=$(date +%Y%m%d)&channel_id=105810"

      - name: Enrich EPG XML with TVmaze and Trakt and fix channel IDs
        run: python3 Backflow/scripts/enrich_southpark.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add Backflow/Manual_Database/AU-South_Park.xml
          git commit -m "Updated South Park EPG $(date +%Y-%m-%d)" || echo "No changes to commit"
          git pull --rebase --autostash
          git push
