name: Update EPG XML Redbulltv

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create individual folder
        run: mkdir -p individual

      - name: Fetch EPG XML
        run: curl -o individual/Redbulltv.xml "https://nzxmltv.com/iptv/redbull.xml"

      - name: Clean and transform EPG XML
        run: |
          # Remove all XML declarations and DOCTYPE lines
          sed -i '/<?xml version=.*?>/d' individual/Redbulltv.xml
          sed -i '/<!DOCTYPE tv SYSTEM.*>/d' individual/Redbulltv.xml

          # Insert the XML declaration + DOCTYPE on a single line at the top
          sed -i '1i<?xml version="1.0" encoding="UTF-8"?> <!DOCTYPE tv SYSTEM "xmltv.dtd">' individual/Redbulltv.xml

          # Replace <channel> block with fixed block
          sed -i '/<channel id=/,/<\/channel>/c\
  <channel id="10001">\
    <display-name lang="US">Red Bull TV</display-name>\
    <icon src="https://i.imgur.com/3IO3vYp.png" />\
  </channel>' individual/Redbulltv.xml

          # Remove all <url> tags
          sed -i '/<url>.*<\/url>/d' individual/Redbulltv.xml

          # Transform <programme> blocks
          perl -0777 -pe '
            s{<programme\b(.*?)>(.*?)</programme>}{
              my ($attrs, $content) = ($1, $2);
              my ($start) = $attrs =~ /start="([^"]*)"/;
              my ($stop) = $attrs =~ /stop="([^"]*)"/;

              # Combine title and subtitle
              my ($title) = $content =~ /<title[^>]*>([^<]*)<\/title>/;
              my ($subtitle) = $content =~ /<sub-title[^>]*>([^<]*)<\/sub-title>/;
              my $fulltitle = $title;
              $fulltitle .= " - $subtitle" if $subtitle;

              # Extract <desc>
              my ($desc) = $content =~ /<desc[^>]*>(.*?)<\/desc>/s;

              # Extract date YYYY-MM-DD from start
              my $date = "";
              if ($start =~ /^(\d{4})(\d{2})(\d{2})/) {
                $date = "$1-$2-$3";
              }

              # Build new programme block
              "<programme channel=\"10001\" start=\"$start\" stop=\"$stop\">\n" .
              "  <title lang=\"en\">$fulltitle</title>\n" .
              "  <desc>$desc</desc>\n" .
              "  <date>$date</date>\n" .
              "</programme>"
            }ges' individual/Redbulltv.xml > individual/Redbulltv.cleaned.xml

          # Overwrite original file
          mv individual/Redbulltv.cleaned.xml individual/Redbulltv.xml

      - name: Commit and push if changed
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add individual/Redbulltv.xml
          git commit -m "Updated EPG $(date +%Y-%m-%d)" || echo "No changes to commit"
          git pull --rebase --autostash
          git push --force
