name: Update EPG XML Hallmark EastUS

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight UTC daily
  workflow_dispatch:  # Allows manual runs

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create individual folder if it doesn't exist
        run: mkdir -p individual

      - name: Fetch EPG XML
        run: curl -o individual/USA-Hallmark_EastUS.xml "https://epg.pw/api/epg.xml?lang=en&date=$(date +%Y%m%d)&channel_id=403490"

      - name: Add XML Declaration and DOCTYPE
        run: |
          sed -i '1s|$| <!DOCTYPE tv SYSTEM "xmltv.dtd">|' individual/USA-Hallmark_EastUS.xml

      - name: Check for Title "The Golden Girls" in XML and Add Icon and Categories
        run: |
          if grep -q '<title lang="zh">The Golden Girls</title>' individual/USA-Hallmark_EastUS.xml; then
            echo "Found The Golden Girls in the EPG XML!"
            sed -i '/<title lang="zh">The Golden Girls<\/title>/a \
            <icon src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-RtHQX9GWo7CL5loJFxzs1PGZa050zqt_2kFOC8RBSed-B54S"/>\
            <category lang="en">Series</category>\
            <category lang="en">Comedy</category>\
            <category lang="en">Drama</category>' individual/USA-Hallmark_EastUS.xml
          else
            echo "The Golden Girls not found in the EPG XML."
          fi

      - name: Check for Title "Mickey Mouse Clubhouse" in XML and Add Icon and Categories
        run: |
          if grep -iq '<title[^>]*>Mickey Mouse Clubhouse</title>' individual/USA-Hallmark_EastUS.xml; then
            echo "Found Mickey Mouse Clubhouse in the EPG XML!"
            sed -i '/<title[^>]*>Mickey Mouse Clubhouse<\/title>/a \
            <icon src="https://play-lh.googleusercontent.com/bqEcu3u2ZXANY_HqhPAgfGvi4_UZ9m7wNHuz3gFjn2Urxw745-D6Va-e4Fh-Im806mMI8kFDhQWAFmLZM7c"/>\
            <category lang="en">Educational</category>\
            <category lang="en">Animation</category>\
            <category lang="en">Comedy</category>\
            <category lang="en">Kids</category>' individual/USA-Hallmark_EastUS.xml
          else
            echo "Mickey Mouse Clubhouse not found in the EPG XML."
          fi


      - name: Commit and push if changed
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add individual/USA-Hallmark_EastUS.xml
          git commit -m "Updated EPG $(date +%Y-%m-%d)" || echo "No changes to commit"
          git pull --rebase --autostash
          git push --force
