name: Update EPG XML Hallmark EastUS

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight UTC daily
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create individual folder if it doesn't exist
        run: mkdir -p individual

      - name: Fetch EPG XML
        run: |
          date=$(LC_ALL=C date +%Y%m%d)
          curl -o individual/USA-Hallmark_EastUS.xml "https://epg.pw/api/epg.xml?lang=en&date=$date&channel_id=403490"

      - name: Add XML Declaration and DOCTYPE on line 1
        run: |
          # Prepend XML declaration and DOCTYPE together as line 1
          sed -i '1s/^/<?xml version="1.0" encoding="UTF-8"?>\n<!DOCTYPE tv SYSTEM "xmltv.dtd">\n/' individual/USA-Hallmark_EastUS.xml

      - name: Pull latest changes before committing
        run: git pull --rebase --autostash

      - name: Commit and push if changed
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add individual/USA-Hallmark_EastUS.xml
          git diff --quiet && git diff --staged --quiet || git commit -m "Updated EPG $(date +%Y-%m-%d)"
          git push --force
