name: Update EPG XML

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight UTC daily
  workflow_dispatch:  # Allows manual runs

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch First EPG XML (Channel 1)
        run: curl -o epg.xml "https://epg.pw/api/epg.xml?lang=en&date=$(date +%Y%m%d)&channel_id=403674"

      - name: Modify First EPG (Check for Bluey)
        run: |
          if grep -q '<title lang="zh">Bluey</title>' epg.xml; then
            echo "Found Bluey in Channel 1!"
            sed -i '/<title lang="zh">Bluey<\/title>/a \
            <icon src="https://static.wikia.nocookie.net/blueypedia/images/4/41/Bluey_logi.png/revision/latest/thumbnail/width/360/height/360?cb=20190120094255"/>\
            <category lang="en">Series</category>\
            <category lang="en">Animation</category>\
            <category lang="en">Comedy</category>\
            <category lang="en">Drama</category>\
            <category lang="en">Kids</category>' epg.xml
          else
            echo "Bluey not found in Channel 1."
          fi

      - name: Fetch Second EPG XML (Channel 2)
        run: curl -o epg2.xml "https://epg.pw/api/epg.xml?lang=en&date=$(date +%Y%m%d)&channel_id=93341"

      - name: Modify Second EPG (Check for Bluey)
        run: |
          if grep -q '<title lang="zh">Bluey</title>' epg2.xml; then
            echo "Found Bluey in Channel 2!"
            sed -i '/<title lang="zh">Bluey<\/title>/a \
            <icon src="https://static.wikia.nocookie.net/blueypedia/images/4/41/Bluey_logi.png/revision/latest/thumbnail/width/360/height/360?cb=20190120094255"/>\
            <category lang="en">Series</category>\
            <category lang="en">Animation</category>\
            <category lang="en">Comedy</category>\
            <category lang="en">Drama</category>\
            <category lang="en">Kids</category>' epg2.xml
          else
            echo "Bluey not found in Channel 2."
          fi

      - name: Append Second EPG Data to First
        run: |
          tail -n +2 epg2.xml >> epg.xml  # Remove first line and append

      - name: Commit and push if changed
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          if [[ -n $(git status --porcelain) ]]; then
            git add epg.xml
            git commit -m "Updated EPG sequentially $(date +%Y-%m-%d)"
            git push
          else
            echo "No changes to commit"
